pc/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pcapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          doument_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pcapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='shop'
urlpatterns = [
    path('',views.allproduct,name='allproduct'),
    path('<slug:c_slug>/',views.allproduct,name='product_by_category'),
    
]

pcapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=50,unique=True)
    slug=models.SlugField(max_length=50,unique=True)
    des=models.TextField(blank=True,null=True)
    image=models.ImageField(upload_to='category',blank=True)
    
    class Meta:
        ordering=('name', )
        verbose_name='category'
        verbose_name_plural='categories'
        
        def __str__(self):
            return '{}'.format (self.name)

class Product(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=50,unique=True)
    slug=models.SlugField(max_length=50,unique=True)
    des=models.TextField(blank=True,null=True)
    image=models.ImageField(upload_to='product',blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2,null=True)
    stock=models.IntegerField(null=True)
    available=models.BooleanField(default=True,null=True)
    created=models.DateTimeField(auto_now_add=True,null=True)
    updated=models.DateTimeField(auto_now=True,null=True)
      
    class Meta:
        ordering=('name', )
        verbose_name='product'
        verbose_name_plural='products'       
         
        def __str__(self):
            return '{}'.format (self.name)
    
    
    

pcapp/views.py
from django.shortcuts import render
from pcapp.models import Product

def allproduct(request,c_slug=None):
    c_page=None
    products=None
    if c_slug!=None:
        c_page=get_or_404(Category,slug=c_slug)
        products=Product.objects.all().filter(category=c_page,available=True)
    else:
        products=Product.objects.all().filter(available=True)
    return render(request,'category.html',{'category':c_page,'products':products})   

templates/base.html
 {% load static %}

 <meta name="description" content="{% block metadescription %}{% endblock %}">

 <title> {% block title %} {% endblock %}

{% include 'navbar.html' %}
{% block content %}
{% endblock %}
<div>
{% include 'footer.html' %}
</div>

templates/category.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
{% if category %}
{{ category.description|truncatewords:155 }}
{% else %}
Welcome to Supreme digital shop 
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
{{ category.name }} - Supreme Digital shop
{% else %}
See our latest collection - Supreme Digital shop
{% endif %}
{% endblock %}

templates/footer.html
<div>
    <p>&copy;  Supreme Computer private limited .All rights reserved </p>
</div>

templates/home.html
<h2>Welcome Boss</h2>

templates/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'shop:allproduct' %}">All Product </a> <li>
    </ul>
</nav>